#!/usr/local/miniconda3/envs/py312/bin/python
"""
Feature Analysis Script - yamnet + FC Projection Feature Space Analysis

Analyzes the features generated by the model's feature extraction pipeline:
  Raw Audio → yamnet log-mel patches → yamnet 128-dim embedding → FC 32-dim feature

Analysis Contents:
1. Feature extraction overview & basic statistics
2. Per-class feature statistics (128-dim yamnet + 32-dim projected)
3. Feature dimension variance analysis
4. Feature distribution visualization (histograms / KDE per class)
5. Inter-feature correlation heatmap
6. Feature space t-SNE / PCA visualization
7. Inter-class distance / similarity analysis
8. Known vs Unknown separability analysis
9. Feature norm & activation pattern analysis
10. Clustering-oriented feature quality assessment (Silhouette, Davies-Bouldin)

Output directory: experiment/feature_analysis/
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib.gridspec import GridSpec
import matplotlib.cm as cm
import os
import sys
from collections import defaultdict, Counter
from sklearn.manifold import TSNE
from sklearn.decomposition import PCA
from sklearn.metrics import pairwise_distances, silhouette_score, davies_bouldin_score
from sklearn.metrics import normalized_mutual_info_score
from scipy.stats import gaussian_kde
from scipy.optimize import linear_sum_assignment
from tqdm import tqdm
import warnings
warnings.filterwarnings('ignore')

# ============================================================
# Configuration
# ============================================================
OUTPUT_DIR = 'experiment/feature_analysis_TAU22_yamnet'
os.makedirs(OUTPUT_DIR, exist_ok=True)

LABEL_MAP = {
    0: 'airport',
    1: 'shopping_mall',
    2: 'metro_station',
    3: 'street_pedestrian',
    4: 'public_square',
    5: 'street_traffic',
    6: 'tram',
    7: 'bus',
    8: 'metro',
    9: 'park'
}

NUM_KNOWN = 6
NUM_CLASSES = 10
SAMPLE_RATE = 16000
MAX_DURATION = 1

CLASS_COLORS = plt.cm.tab10(np.linspace(0, 1, 10))

plt.rcParams['font.size'] = 10
plt.rcParams['figure.dpi'] = 150
plt.rcParams['savefig.dpi'] = 150
plt.rcParams['savefig.bbox'] = 'tight'
plt.rcParams['savefig.pad_inches'] = 0.3
plt.rcParams['axes.linewidth'] = 0.5
plt.rcParams['axes.edgecolor'] = '#cccccc'

# ============================================================
# Feature Extraction Hook
# ============================================================
class FeatureExtractor:
    """Extract intermediate features from the FinalModel pipeline."""

    def __init__(self, model, device='cuda'):
        self.model = model
        self.device = device
        self.model.eval()

        self._yamnet_features = None
        self._fc1_features = None
        self._fc2_features = None
        self._final_features = None

        # Register forward hooks
        self._hooks = []
        self._hooks.append(self.model.feature_model.register_forward_hook(self._hook_yamnet))
        self._hooks.append(self.model.fc1.register_forward_hook(self._hook_fc1))
        self._hooks.append(self.model.fc2.register_forward_hook(self._hook_fc2))
        self._hooks.append(self.model.fc3.register_forward_hook(self._hook_fc3))

    def _hook_yamnet(self, module, input, output):
        self._yamnet_features = output.detach()

    def _hook_fc1(self, module, input, output):
        self._fc1_features = output.detach()

    def _hook_fc2(self, module, input, output):
        self._fc2_features = output.detach()

    def _hook_fc3(self, module, input, output):
        self._final_features = output.detach()

    def remove_hooks(self):
        for h in self._hooks:
            h.remove()

    @torch.no_grad()
    def extract_batch(self, waveforms):
        """
        Run a batch of waveforms through the model and collect all features.
        Returns dict with keys: 'yamnet_128', 'fc1_128', 'fc2_64', 'final_32',
        plus all model outputs.
        """
        self._yamnet_features = None
        self._fc1_features = None
        self._fc2_features = None
        self._final_features = None

        waveforms = waveforms.to(self.device)
        known_outputs, unknown_outputs, unknown_outputs_aug, weights1, weights2 = self.model(waveforms)

        result = {
            'yamnet_128': self._yamnet_features.cpu(),
            'fc1_128': self._fc1_features.cpu(),
            'fc2_64': self._fc2_features.cpu(),
            'final_32': self._final_features.cpu(),
            'known_outputs': known_outputs.cpu(),
            'unknown_outputs': unknown_outputs.cpu(),
            'weights1': weights1.cpu(),
            'weights2': weights2.cpu(),
        }
        return result


# ============================================================
# Data Loading Utility
# ============================================================
from utils.TAU22 import TAUDataset

def get_label_idx(target_tensor):
    """Get class index from one-hot target tensor."""
    return target_tensor.squeeze().argmax().item()


# ============================================================
# Feature Collection (batch processing)
# ============================================================
def collect_features(model, dataset, device='cuda', max_samples_per_class=None,
                     batch_size=256, split_name='calib'):
    """
    Run all samples through model and collect features per class.
    Returns:
        features_dict: {class_id: {'yamnet_128': np.array, 'fc1_128': ..., ...}}
        all_features: {'yamnet_128': np.array, ...} (concatenated across all samples)
        all_labels: np.array of class indices
    """
    print(f"\n  Collecting features from '{split_name}' split (batch_size={batch_size})...")

    extractor = FeatureExtractor(model, device)

    class_data = defaultdict(lambda: {
        'yamnet_128': [], 'fc1_128': [], 'fc2_64': [], 'final_32': [],
        'known_outputs': [], 'unknown_outputs': [], 'weights1': [], 'weights2': []
    })
    class_counts = defaultdict(int)

    loader = torch.utils.data.DataLoader(
        dataset, batch_size=batch_size, shuffle=False,
        num_workers=8, pin_memory=True, drop_last=False
    )

    for batch_idx, item in enumerate(tqdm(loader, desc='  Extracting features')):
        waveforms = item['source_audio']
        targets = item['target'].squeeze(1)
        label_indices = targets.argmax(dim=1).tolist()

        # Check if we need to skip some classes
        skip_mask = []
        for idx in label_indices:
            if max_samples_per_class is not None and class_counts[idx] >= max_samples_per_class:
                skip_mask.append(True)
            else:
                skip_mask.append(False)

        if all(skip_mask):
            continue

        result = extractor.extract_batch(waveforms)

        for i, cls_id in enumerate(label_indices):
            if skip_mask[i]:
                continue
            class_counts[cls_id] += 1
            for key in ['yamnet_128', 'fc1_128', 'fc2_64', 'final_32',
                         'known_outputs', 'unknown_outputs', 'weights1', 'weights2']:
                class_data[cls_id][key].append(result[key][i].numpy())

    extractor.remove_hooks()

    # Concatenate per class
    for cls_id in class_data:
        for key in class_data[cls_id]:
            class_data[cls_id][key] = np.array(class_data[cls_id][key])

    # Build all_features and all_labels
    all_features = {}
    all_labels = []
    all_feature_keys = ['yamnet_128', 'fc1_128', 'fc2_64', 'final_32',
                        'known_outputs', 'unknown_outputs', 'weights1', 'weights2']
    for key in all_feature_keys:
        arrays = []
        labels_part = []
        for cls_id in range(NUM_CLASSES):
            if cls_id in class_data and len(class_data[cls_id][key]) > 0:
                arrays.append(class_data[cls_id][key])
                labels_part.extend([cls_id] * len(class_data[cls_id][key]))
        if arrays:
            all_features[key] = np.concatenate(arrays, axis=0)
        else:
            all_features[key] = np.array([])
        if key == 'final_32':
            all_labels = np.array(labels_part)

    total = len(all_labels)
    print(f"  Collected features for {total} samples:")
    for cls_id in range(NUM_CLASSES):
        cnt = class_counts.get(cls_id, 0)
        role = "Known" if cls_id < NUM_KNOWN else "Unknown"
        print(f"    Class {cls_id:2d} ({LABEL_MAP[cls_id]:20s}, {role}): {cnt}")

    return class_data, all_features, all_labels


# ============================================================
# Analysis 1: Feature Extraction Overview
# ============================================================
def analyze_overview(all_features, all_labels):
    """Basic statistics of each feature layer."""
    print("\n" + "=" * 70)
    print("Analysis 1: Feature Extraction Overview")
    print("=" * 70)

    feature_keys = ['yamnet_128', 'fc1_128', 'fc2_64', 'final_32']
    feature_names = ['yamnet 128-d', 'FC1 128-d', 'FC2 64-d', 'Final 32-d (Tanh)']

    fig, axes = plt.subplots(2, 4, figsize=(20, 8))

    for i, (key, name) in enumerate(zip(feature_keys, feature_names)):
        data = all_features[key]
        print(f"\n  {name}:")
        print(f"    Shape: {data.shape}")
        print(f"    Mean:  {data.mean():.6f}")
        print(f"    Std:   {data.std():.6f}")
        print(f"    Min:   {data.min():.6f}")
        print(f"    Max:   {data.max():.6f}")
        print(f"    Median: {np.median(data):.6f}")

        # Histogram of all values
        ax = axes[0, i]
        ax.hist(data.flatten(), bins=200, density=True, alpha=0.7, color='steelblue', edgecolor='none')
        ax.set_title(f'{name}\nμ={data.mean():.3f}, σ={data.std():.3f}', fontsize=10)
        ax.set_xlabel('Value')
        ax.set_ylabel('Density')
        ax.grid(alpha=0.3)

        # Per-dimension mean/std
        ax = axes[1, i]
        dim_means = data.mean(axis=0)
        dim_stds = data.std(axis=0)
        x = np.arange(len(dim_means))
        ax.bar(x, dim_means, yerr=dim_stds, color='steelblue', alpha=0.7,
               edgecolor='none', capsize=2, error_kw={'linewidth': 0.5})
        ax.set_title(f'{name} - Per-Dim Mean ± Std', fontsize=10)
        ax.set_xlabel('Dimension')
        ax.set_ylabel('Mean Value')
        ax.grid(alpha=0.3, axis='y')

    plt.suptitle('Feature Extraction Pipeline Overview', fontsize=14, fontweight='bold')
    plt.tight_layout()
    plt.savefig(f'{OUTPUT_DIR}/01_feature_overview.png', facecolor='white')
    plt.close()
    print(f"\n  [OK] Saved: {OUTPUT_DIR}/01_feature_overview.png")


# ============================================================
# Analysis 2: Per-Class Feature Statistics
# ============================================================
def analyze_per_class_stats(class_data):
    """Detailed per-class feature statistics."""
    print("\n" + "=" * 70)
    print("Analysis 2: Per-Class Feature Statistics")
    print("=" * 70)

    feature_keys = ['yamnet_128', 'fc1_128', 'fc2_64', 'final_32']
    feature_names = ['yamnet 128-d', 'FC1 128-d', 'FC2 64-d', 'Final 32-d']

    for key, name in zip(feature_keys, feature_names):
        print(f"\n  --- {name} ---")
        print(f"  {'Class':20s} {'Mean':>10s} {'Std':>10s} {'Min':>10s} {'Max':>10s} {'L2-Norm':>10s}")
        print("  " + "-" * 75)

        for cls_id in range(NUM_CLASSES):
            if cls_id in class_data and len(class_data[cls_id][key]) > 0:
                d = class_data[cls_id][key]
                norms = np.sqrt(np.sum(d ** 2, axis=1))
                role = "K" if cls_id < NUM_KNOWN else "U"
                print(f"  {LABEL_MAP[cls_id]:20s} "
                      f"{d.mean():10.4f} {d.std():10.4f} "
                      f"{d.min():10.4f} {d.max():10.4f} "
                      f"{norms.mean():10.4f}  [{role}]")

    # Visualize per-class mean feature vectors for final 32-d
    fig, axes = plt.subplots(2, 1, figsize=(16, 10))

    for layer_key, layer_name, ax_idx in [('final_32', 'Final 32-d Feature', 0),
                                           ('yamnet_128', 'yamnet 128-d Embedding', 1)]:
        ax = axes[ax_idx]
        n_dims = class_data[0][layer_key].shape[1] if 0 in class_data else 32
        for cls_id in range(NUM_CLASSES):
            if cls_id in class_data and len(class_data[cls_id][layer_key]) > 0:
                mean_vec = class_data[cls_id][layer_key].mean(axis=0)
                marker = 'o-' if cls_id < NUM_KNOWN else 's--'
                lw = 1.5 if cls_id < NUM_KNOWN else 1.0
                ax.plot(range(n_dims), mean_vec, marker, color=CLASS_COLORS[cls_id],
                        label=LABEL_MAP[cls_id], linewidth=lw, markersize=3, alpha=0.8)

        ax.set_title(f'Per-Class Mean {layer_name}', fontsize=12, fontweight='bold')
        ax.set_xlabel('Dimension')
        ax.set_ylabel('Mean Value')
        ax.legend(fontsize=7, ncol=2, loc='best')
        ax.grid(alpha=0.3)
        ax.axvline(x=-0.5, color='red', linestyle=':', alpha=0.3)

    plt.suptitle('Per-Class Mean Feature Profiles', fontsize=14, fontweight='bold')
    plt.tight_layout()
    plt.savefig(f'{OUTPUT_DIR}/02_per_class_feature_profiles.png', facecolor='white')
    plt.close()
    print(f"\n  [OK] Saved: {OUTPUT_DIR}/02_per_class_feature_profiles.png")


# ============================================================
# Analysis 3: Feature Dimension Variance Analysis
# ============================================================
def analyze_dimension_variance(all_features, all_labels):
    """Analyze variance explained by each feature dimension."""
    print("\n" + "=" * 70)
    print("Analysis 3: Feature Dimension Variance Analysis")
    print("=" * 70)

    fig, axes = plt.subplots(1, 3, figsize=(18, 5))

    for ax_idx, (key, name) in enumerate([
        ('yamnet_128', 'yamnet 128-d'),
        ('fc2_64', 'FC2 64-d'),
        ('final_32', 'Final 32-d')
    ]):
        data = all_features[key]
        dim_vars = data.var(axis=0)
        dim_means = data.mean(axis=0)
        dim_abs_mean = np.abs(dim_means)

        total_var = dim_vars.sum()
        var_ratio = dim_vars / total_var * 100
        cum_var = np.cumsum(var_ratio)

        ax = axes[ax_idx]
        x = np.arange(len(dim_vars))

        ax2 = ax.twinx()
        ax.bar(x, var_ratio, color='steelblue', alpha=0.6, label='Variance %')
        ax2.plot(x, cum_var, 'r-o', markersize=3, linewidth=1.5, label='Cumulative %')
        ax2.axhline(y=90, color='green', linestyle='--', alpha=0.5, label='90% threshold')
        ax2.axhline(y=95, color='orange', linestyle='--', alpha=0.5, label='95% threshold')

        # Mark low-variance dimensions
        low_var_threshold = 0.01 * var_ratio.max()
        low_var_dims = np.where(var_ratio < low_var_threshold)[0]
        if len(low_var_dims) > 0:
            ax.bar(low_var_dims, var_ratio[low_var_dims], color='red', alpha=0.4, label=f'Low var ({len(low_var_dims)})')

        ax.set_title(f'{name}\nTotal Var: {total_var:.2f}', fontsize=11, fontweight='bold')
        ax.set_xlabel('Dimension')
        ax.set_ylabel('Variance %', color='steelblue')
        ax2.set_ylabel('Cumulative %', color='red')
        ax.legend(fontsize=7, loc='upper left')
        ax2.legend(fontsize=7, loc='center right')
        ax.grid(alpha=0.2)

        # Print top dimensions
        top_k = min(10, len(dim_vars))
        top_dims = np.argsort(dim_vars)[::-1][:top_k]
        print(f"\n  {name} - Top {top_k} dimensions by variance:")
        for rank, dim in enumerate(top_dims):
            print(f"    Dim {dim:3d}: var={dim_vars[dim]:.6f} ({var_ratio[dim]:.2f}%), "
                  f"cum={cum_var[dim]:.1f}%")

        dims_90 = np.searchsorted(cum_var, 90) + 1
        dims_95 = np.searchsorted(cum_var, 95) + 1
        print(f"  Dimensions for 90% variance: {dims_90}/{len(dim_vars)}")
        print(f"  Dimensions for 95% variance: {dims_95}/{len(dim_vars)}")

    plt.suptitle('Per-Dimension Variance Explained', fontsize=14, fontweight='bold')
    plt.tight_layout()
    plt.savefig(f'{OUTPUT_DIR}/03_dimension_variance.png', facecolor='white')
    plt.close()
    print(f"\n  [OK] Saved: {OUTPUT_DIR}/03_dimension_variance.png")


# ============================================================
# Analysis 4: Feature Distribution per Class
# ============================================================
def analyze_feature_distributions(class_data, n_dims_to_show=8):
    """Visualize feature value distributions per class."""
    print("\n" + "=" * 70)
    print("Analysis 4: Feature Distribution per Class")
    print("=" * 70)

    # Final 32-d: show first n_dims_to_show dimensions
    key = 'final_32'
    fig, axes = plt.subplots(2, n_dims_to_show // 2, figsize=(4 * n_dims_to_show // 2, 8))

    for dim_i in range(min(n_dims_to_show, 32)):
        row, col = dim_i // (n_dims_to_show // 2), dim_i % (n_dims_to_show // 2)
        ax = axes[row, col]

        for cls_id in range(NUM_CLASSES):
            if cls_id in class_data and len(class_data[cls_id][key]) > 0:
                values = class_data[cls_id][key][:, dim_i]
                alpha = 0.4 if cls_id < NUM_KNOWN else 0.3
                lw = 1.2 if cls_id < NUM_KNOWN else 0.8
                ls = '-' if cls_id < NUM_KNOWN else '--'
                ax.hist(values, bins=50, density=True, alpha=alpha,
                        color=CLASS_COLORS[cls_id], histtype='stepfilled', linewidth=0)
                # KDE overlay
                try:
                    kde = gaussian_kde(values, bw_method=0.3)
                    x_grid = np.linspace(values.min() - 0.5, values.max() + 0.5, 200)
                    ax.plot(x_grid, kde(x_grid), color=CLASS_COLORS[cls_id],
                            linewidth=lw, linestyle=ls, alpha=0.8)
                except Exception:
                    pass

        ax.set_title(f'Dim {dim_i}', fontsize=10, fontweight='bold')
        ax.grid(alpha=0.2)

    # Add legend to first subplot
    handles = []
    for cls_id in range(NUM_CLASSES):
        role = "K" if cls_id < NUM_KNOWN else "U"
        handles.append(plt.Line2D([0], [0], color=CLASS_COLORS[cls_id],
                                  linestyle='-' if cls_id < NUM_KNOWN else '--',
                                  label=f'{LABEL_MAP[cls_id]}({role})'))
    axes[0, 0].legend(handles=handles, fontsize=5, ncol=2, loc='upper right')

    plt.suptitle(f'Final 32-d Feature Distributions (First {n_dims_to_show} Dims)\n'
                 '(Solid=Known, Dashed=Unknown)', fontsize=14, fontweight='bold')
    plt.tight_layout()
    plt.savefig(f'{OUTPUT_DIR}/04_feature_distributions.png', facecolor='white')
    plt.close()
    print(f"  [OK] Saved: {OUTPUT_DIR}/04_feature_distributions.png")

    # Also show yamnet 128-d: select top-4 dimensions by variance
    yamnet_data = {}
    for cls_id in range(NUM_CLASSES):
        if cls_id in class_data:
            yamnet_data[cls_id] = class_data[cls_id]['yamnet_128']
    all_vgg = np.concatenate([v for v in yamnet_data.values()], axis=0)
    top_dims = np.argsort(all_vgg.var(axis=0))[::-1][:4]

    fig, axes = plt.subplots(1, 4, figsize=(20, 4))
    for ax_i, dim_i in enumerate(top_dims):
        ax = axes[ax_i]
        for cls_id in range(NUM_CLASSES):
            if cls_id in yamnet_data:
                values = yamnet_data[cls_id][:, dim_i]
                ax.hist(values, bins=50, density=True, alpha=0.3,
                        color=CLASS_COLORS[cls_id], histtype='stepfilled')
        ax.set_title(f'yamnet Dim {dim_i} (high variance)', fontsize=10, fontweight='bold')
        ax.grid(alpha=0.2)

    axes[0].legend(handles=handles, fontsize=5, ncol=2, loc='upper right')
    plt.suptitle('yamnet 128-d: Top-4 High-Variance Dimensions', fontsize=14, fontweight='bold')
    plt.tight_layout()
    plt.savefig(f'{OUTPUT_DIR}/04_yamnet_top_dims.png', facecolor='white')
    plt.close()
    print(f"  [OK] Saved: {OUTPUT_DIR}/04_yamnet_top_dims.png")


# ============================================================
# Analysis 5: Inter-Feature Correlation
# ============================================================
def analyze_correlation(all_features, all_labels):
    """Analyze correlation between feature dimensions."""
    print("\n" + "=" * 70)
    print("Analysis 5: Inter-Feature Correlation Analysis")
    print("=" * 70)

    fig, axes = plt.subplots(1, 3, figsize=(22, 6))

    for ax_idx, (key, name) in enumerate([
        ('yamnet_128', 'yamnet 128-d'),
        ('fc2_64', 'FC2 64-d'),
        ('final_32', 'Final 32-d')
    ]):
        data = all_features[key]
        corr = np.corrcoef(data.T)

        if corr.shape[0] > 64:
            # For yamnet, show a smaller block for readability
            ax = axes[ax_idx]
            im = ax.imshow(corr, cmap='RdBu_r', vmin=-1, vmax=1, aspect='auto')
            ax.set_title(f'{name} Correlation', fontsize=11, fontweight='bold')
        else:
            ax = axes[ax_idx]
            im = ax.imshow(corr, cmap='RdBu_r', vmin=-1, vmax=1, aspect='auto')
            ax.set_title(f'{name} Correlation', fontsize=11, fontweight='bold')

            # Annotate for small matrices
            if corr.shape[0] <= 32:
                for i in range(corr.shape[0]):
                    for j in range(corr.shape[1]):
                        text_color = 'white' if abs(corr[i, j]) > 0.5 else 'black'
                        ax.text(j, i, f'{corr[i,j]:.2f}', ha='center', va='center',
                                fontsize=5, color=text_color)

        ax.set_xlabel('Dimension')
        ax.set_ylabel('Dimension')
        plt.colorbar(im, ax=ax, shrink=0.8)

        # Statistics
        n_dims = corr.shape[0]
        upper_tri = corr[np.triu_indices(n_dims, k=1)]
        print(f"\n  {name}:")
        print(f"    Mean |corr|: {np.mean(np.abs(upper_tri)):.4f}")
        print(f"    Max corr:    {np.max(upper_tri):.4f}")
        print(f"    Min corr:    {np.min(upper_tri):.4f}")
        high_corr = np.sum(np.abs(upper_tri) > 0.8)
        print(f"    Pairs with |corr|>0.8: {high_corr}/{len(upper_tri)}")

    plt.suptitle('Inter-Dimension Correlation Matrices', fontsize=14, fontweight='bold')
    plt.tight_layout()
    plt.savefig(f'{OUTPUT_DIR}/05_correlation_matrices.png', facecolor='white')
    plt.close()
    print(f"\n  [OK] Saved: {OUTPUT_DIR}/05_correlation_matrices.png")


# ============================================================
# Analysis 6: Feature Space t-SNE / PCA Visualization
# ============================================================
def analyze_feature_space_visualization(all_features, all_labels):
    """t-SNE and PCA visualization of the feature space."""
    print("\n" + "=" * 70)
    print("Analysis 6: Feature Space Visualization (t-SNE / PCA)")
    print("=" * 70)

    fig, axes = plt.subplots(2, 3, figsize=(22, 14))

    layers = [
        ('yamnet_128', 'yamnet 128-d'),
        ('fc2_64', 'FC2 64-d'),
        ('final_32', 'Final 32-d')
    ]

    for col, (key, name) in enumerate(layers):
        data = all_features[key]
        labels = all_labels

        print(f"\n  Processing {name}...")

        # PCA
        pca = PCA(n_components=2)
        X_pca = pca.fit_transform(data)
        print(f"    PCA explained variance: {pca.explained_variance_ratio_}")

        # t-SNE (use subsample if too large)
        if len(data) > 3000:
            idx = np.random.choice(len(data), 3000, replace=False)
            tsne_input = data[idx]
            tsne_labels = labels[idx]
        else:
            tsne_input = data
            tsne_labels = labels

        tsne = TSNE(n_components=2, random_state=42, perplexity=30, max_iter=1000)
        X_tsne = tsne.fit_transform(tsne_input)

        # Plot PCA
        ax = axes[0, col]
        for cls_id in range(NUM_CLASSES):
            mask = labels == cls_id
            marker = 'o' if cls_id < NUM_KNOWN else 's'
            role = "Known" if cls_id < NUM_KNOWN else "Unknown"
            ax.scatter(X_pca[mask, 0], X_pca[mask, 1],
                      c=[CLASS_COLORS[cls_id]], marker=marker, s=10, alpha=0.5,
                      edgecolors='white', linewidth=0.2,
                      label=f'{LABEL_MAP[cls_id]}({role})')
        ax.set_title(f'{name} - PCA\n'
                     f'PC1={100*pca.explained_variance_ratio_[0]:.1f}%, '
                     f'PC2={100*pca.explained_variance_ratio_[1]:.1f}%',
                     fontsize=10, fontweight='bold')
        ax.set_xlabel('PC1')
        ax.set_ylabel('PC2')
        ax.legend(fontsize=5, ncol=2, loc='best')
        ax.grid(alpha=0.2)

        # Plot t-SNE
        ax = axes[1, col]
        for cls_id in range(NUM_CLASSES):
            mask = tsne_labels == cls_id
            marker = 'o' if cls_id < NUM_KNOWN else 's'
            role = "Known" if cls_id < NUM_KNOWN else "Unknown"
            ax.scatter(X_tsne[mask, 0], X_tsne[mask, 1],
                      c=[CLASS_COLORS[cls_id]], marker=marker, s=10, alpha=0.5,
                      edgecolors='white', linewidth=0.2,
                      label=f'{LABEL_MAP[cls_id]}({role})')
        ax.set_title(f'{name} - t-SNE', fontsize=10, fontweight='bold')
        ax.set_xlabel('t-SNE 1')
        ax.set_ylabel('t-SNE 2')
        ax.legend(fontsize=5, ncol=2, loc='best')
        ax.grid(alpha=0.2)

    plt.suptitle('Feature Space Visualization\n(o=Known classes, s=Unknown classes)',
                 fontsize=14, fontweight='bold')
    plt.tight_layout()
    plt.savefig(f'{OUTPUT_DIR}/06_feature_space_visualization.png', facecolor='white')
    plt.close()
    print(f"\n  [OK] Saved: {OUTPUT_DIR}/06_feature_space_visualization.png")


# ============================================================
# Analysis 7: Inter-Class Distance / Similarity
# ============================================================
def analyze_inter_class_distance(class_data):
    """Compute and visualize inter-class distances in feature space."""
    print("\n" + "=" * 70)
    print("Analysis 7: Inter-Class Distance & Similarity")
    print("=" * 70)

    fig, axes = plt.subplots(1, 3, figsize=(22, 6))

    for ax_idx, (key, name) in enumerate([
        ('yamnet_128', 'yamnet 128-d'),
        ('fc2_64', 'FC2 64-d'),
        ('final_32', 'Final 32-d')
    ]):
        # Compute class centroids
        centroids = []
        valid_classes = []
        for cls_id in range(NUM_CLASSES):
            if cls_id in class_data and len(class_data[cls_id][key]) > 0:
                centroids.append(class_data[cls_id][key].mean(axis=0))
                valid_classes.append(cls_id)
        centroids = np.array(centroids)

        # Distance matrices
        cos_dist = pairwise_distances(centroids, metric='cosine')
        euc_dist = pairwise_distances(centroids, metric='euclidean')
        cos_sim = 1 - cos_dist

        # Plot cosine similarity
        ax = axes[ax_idx]
        im = ax.imshow(cos_sim, cmap='RdYlBu_r', vmin=0, vmax=1)

        ax.set_xticks(range(len(valid_classes)))
        ax.set_yticks(range(len(valid_classes)))
        ax.set_xticklabels([LABEL_MAP[i][:6] for i in valid_classes], rotation=45, ha='right', fontsize=8)
        ax.set_yticklabels([LABEL_MAP[i][:6] for i in valid_classes], fontsize=8)

        for i in range(len(valid_classes)):
            for j in range(len(valid_classes)):
                text_color = 'white' if cos_sim[i, j] > 0.7 else 'black'
                ax.text(j, i, f'{cos_sim[i,j]:.2f}', ha='center', va='center',
                       fontsize=7, color=text_color, fontweight='bold')

        ax.axhline(y=sum(1 for c in valid_classes if c < NUM_KNOWN) - 0.5,
                   color='red', linewidth=2)
        ax.axvline(x=sum(1 for c in valid_classes if c < NUM_KNOWN) - 0.5,
                   color='red', linewidth=2)

        plt.colorbar(im, ax=ax, shrink=0.8)
        ax.set_title(f'{name} - Cosine Similarity', fontsize=11, fontweight='bold')

        # Print intra-group vs inter-group statistics
        known_idx = [i for i, c in enumerate(valid_classes) if c < NUM_KNOWN]
        unknown_idx = [i for i, c in enumerate(valid_classes) if c >= NUM_KNOWN]

        if known_idx and unknown_idx:
            known_known = [cos_sim[i, j] for i in known_idx for j in known_idx if i != j]
            unknown_unknown = [cos_sim[i, j] for i in unknown_idx for j in unknown_idx if i != j]
            known_unknown = [cos_sim[i, j] for i in known_idx for j in unknown_idx]

            print(f"\n  {name}:")
            print(f"    Known-Known avg similarity:    {np.mean(known_known):.4f}")
            print(f"    Unknown-Unknown avg similarity: {np.mean(unknown_unknown):.4f}")
            print(f"    Known-Unknown avg similarity:   {np.mean(known_unknown):.4f}")
            print(f"    Separability (KU - avg(KK,UU)): "
                  f"{np.mean(known_unknown) - 0.5*(np.mean(known_known) + np.mean(unknown_unknown)):.4f}")

    plt.suptitle('Inter-Class Cosine Similarity Matrices\n(Red lines: Known/Unknown boundary)',
                 fontsize=14, fontweight='bold')
    plt.tight_layout()
    plt.savefig(f'{OUTPUT_DIR}/07_inter_class_similarity.png', facecolor='white')
    plt.close()
    print(f"\n  [OK] Saved: {OUTPUT_DIR}/07_inter_class_similarity.png")

    # Also show Euclidean distance
    fig, axes = plt.subplots(1, 3, figsize=(22, 6))

    for ax_idx, (key, name) in enumerate([
        ('yamnet_128', 'yamnet 128-d'),
        ('fc2_64', 'FC2 64-d'),
        ('final_32', 'Final 32-d')
    ]):
        centroids = []
        valid_classes = []
        for cls_id in range(NUM_CLASSES):
            if cls_id in class_data and len(class_data[cls_id][key]) > 0:
                centroids.append(class_data[cls_id][key].mean(axis=0))
                valid_classes.append(cls_id)
        centroids = np.array(centroids)

        euc_dist = pairwise_distances(centroids, metric='euclidean')

        ax = axes[ax_idx]
        im = ax.imshow(euc_dist, cmap='YlOrRd')

        ax.set_xticks(range(len(valid_classes)))
        ax.set_yticks(range(len(valid_classes)))
        ax.set_xticklabels([LABEL_MAP[i][:6] for i in valid_classes], rotation=45, ha='right', fontsize=8)
        ax.set_yticklabels([LABEL_MAP[i][:6] for i in valid_classes], fontsize=8)

        for i in range(len(valid_classes)):
            for j in range(len(valid_classes)):
                text_color = 'white' if euc_dist[i, j] > euc_dist.max() * 0.7 else 'black'
                ax.text(j, i, f'{euc_dist[i,j]:.2f}', ha='center', va='center',
                       fontsize=6, color=text_color)

        ax.axhline(y=sum(1 for c in valid_classes if c < NUM_KNOWN) - 0.5, color='blue', linewidth=2)
        ax.axvline(x=sum(1 for c in valid_classes if c < NUM_KNOWN) - 0.5, color='blue', linewidth=2)

        plt.colorbar(im, ax=ax, shrink=0.8)
        ax.set_title(f'{name} - Euclidean Distance', fontsize=11, fontweight='bold')

    plt.suptitle('Inter-Class Euclidean Distance Matrices\n(Blue lines: Known/Unknown boundary)',
                 fontsize=14, fontweight='bold')
    plt.tight_layout()
    plt.savefig(f'{OUTPUT_DIR}/07_inter_class_euclidean.png', facecolor='white')
    plt.close()
    print(f"  [OK] Saved: {OUTPUT_DIR}/07_inter_class_euclidean.png")


# ============================================================
# Analysis 8: Known vs Unknown Separability
# ============================================================
def analyze_known_vs_unknown(all_features, all_labels):
    """Analyze how well features separate known from unknown classes."""
    print("\n" + "=" * 70)
    print("Analysis 8: Known vs Unknown Separability Analysis")
    print("=" * 70)

    known_mask = all_labels < NUM_KNOWN
    unknown_mask = all_labels >= NUM_KNOWN

    fig, axes = plt.subplots(1, 3, figsize=(20, 6))

    for ax_idx, (key, name) in enumerate([
        ('yamnet_128', 'yamnet 128-d'),
        ('fc2_64', 'FC2 64-d'),
        ('final_32', 'Final 32-d')
    ]):
        data = all_features[key]

        # L2 norm distribution
        known_norms = np.sqrt(np.sum(data[known_mask] ** 2, axis=1))
        unknown_norms = np.sqrt(np.sum(data[unknown_mask] ** 2, axis=1))

        ax = axes[ax_idx]
        ax.hist(known_norms, bins=80, density=True, alpha=0.5, color='coral',
                label=f'Known (n={known_mask.sum()})')
        ax.hist(unknown_norms, bins=80, density=True, alpha=0.5, color='steelblue',
                label=f'Unknown (n={unknown_mask.sum()})')
        ax.set_title(f'{name} - L2 Norm Distribution', fontsize=11, fontweight='bold')
        ax.set_xlabel('L2 Norm')
        ax.set_ylabel('Density')
        ax.legend(fontsize=8)
        ax.grid(alpha=0.3)

        print(f"\n  {name}:")
        print(f"    Known L2 norm:   {known_norms.mean():.4f} ± {known_norms.std():.4f}")
        print(f"    Unknown L2 norm: {unknown_norms.mean():.4f} ± {unknown_norms.std():.4f}")

        # Per-dimension separability (Cohen's d)
        known_data = data[known_mask]
        unknown_data = data[unknown_mask]
        n_dims = data.shape[1]
        cohens_d = np.zeros(n_dims)
        for d in range(n_dims):
            k = known_data[:, d]
            u = unknown_data[:, d]
            pooled_std = np.sqrt((np.var(k) + np.var(u)) / 2)
            cohens_d[d] = (u.mean() - k.mean()) / pooled_std if pooled_std > 0 else 0

        top_separable = np.argsort(np.abs(cohens_d))[::-1][:5]
        print(f"    Top-5 separable dims (Cohen's d):")
        for dim in top_separable:
            print(f"      Dim {dim}: d={cohens_d[dim]:.4f} "
                  f"(K={known_data[:,dim].mean():.4f}, U={unknown_data[:,dim].mean():.4f})")

    plt.suptitle('Known vs Unknown Separability Analysis', fontsize=14, fontweight='bold')
    plt.tight_layout()
    plt.savefig(f'{OUTPUT_DIR}/08_known_vs_unknown.png', facecolor='white')
    plt.close()
    print(f"\n  [OK] Saved: {OUTPUT_DIR}/08_known_vs_unknown.png")

    # Additional: per-dimension Cohen's d bar chart for final 32-d
    data = all_features['final_32']
    known_data = data[known_mask]
    unknown_data = data[unknown_mask]
    cohens_d = np.zeros(32)
    for d in range(32):
        k = known_data[:, d]
        u = unknown_data[:, d]
        pooled_std = np.sqrt((np.var(k) + np.var(u)) / 2)
        cohens_d[d] = (u.mean() - k.mean()) / pooled_std if pooled_std > 0 else 0

    fig, ax = plt.subplots(figsize=(14, 5))
    colors = ['coral' if d > 0 else 'steelblue' for d in cohens_d]
    bars = ax.bar(range(32), cohens_d, color=colors, alpha=0.7, edgecolor='none')
    ax.axhline(y=0, color='black', linewidth=0.5)
    ax.axhline(y=0.2, color='green', linestyle='--', alpha=0.5, label='Small effect (0.2)')
    ax.axhline(y=0.5, color='orange', linestyle='--', alpha=0.5, label='Medium effect (0.5)')
    ax.axhline(y=0.8, color='red', linestyle='--', alpha=0.5, label='Large effect (0.8)')
    ax.axhline(y=-0.2, color='green', linestyle='--', alpha=0.5)
    ax.axhline(y=-0.5, color='orange', linestyle='--', alpha=0.5)
    ax.axhline(y=-0.8, color='red', linestyle='--', alpha=0.5)
    ax.set_xlabel('Dimension')
    ax.set_ylabel("Cohen's d (Unknown - Known)")
    ax.set_title("Final 32-d: Per-Dimension Known vs Unknown Effect Size (Cohen's d)",
                 fontsize=12, fontweight='bold')
    ax.legend(fontsize=8)
    ax.grid(alpha=0.3, axis='y')
    plt.tight_layout()
    plt.savefig(f'{OUTPUT_DIR}/08_cohens_d.png', facecolor='white')
    plt.close()
    print(f"  [OK] Saved: {OUTPUT_DIR}/08_cohens_d.png")


# ============================================================
# Analysis 9: Feature Norm & Activation Pattern
# ============================================================
def analyze_feature_norms(class_data):
    """Analyze feature norms and activation patterns across layers."""
    print("\n" + "=" * 70)
    print("Analysis 9: Feature Norm & Activation Pattern Analysis")
    print("=" * 70)

    fig, axes = plt.subplots(2, 4, figsize=(20, 10))

    layers = [
        ('yamnet_128', 'yamnet 128-d'),
        ('fc1_128', 'FC1 128-d'),
        ('fc2_64', 'FC2 64-d'),
        ('final_32', 'Final 32-d (Tanh)')
    ]

    for col, (key, name) in enumerate(layers):
        # L2 norm per class
        ax = axes[0, col]
        norm_data = []
        labels_list = []
        for cls_id in range(NUM_CLASSES):
            if cls_id in class_data and len(class_data[cls_id][key]) > 0:
                d = class_data[cls_id][key]
                norms = np.sqrt(np.sum(d ** 2, axis=1))
                norm_data.append(norms)
                labels_list.append(LABEL_MAP[cls_id][:6])

        bp = ax.boxplot(norm_data, patch_artist=True, labels=labels_list)
        for patch, cls_id in zip(bp['boxes'], range(NUM_CLASSES)):
            patch.set_facecolor(CLASS_COLORS[cls_id])
            patch.set_edgecolor('#666666')
            patch.set_linewidth(0.5)
        ax.axvline(x=NUM_KNOWN + 0.5, color='red', linestyle='--', linewidth=1.5)
        ax.set_title(f'{name}\nL2 Norm', fontsize=10, fontweight='bold')
        ax.tick_params(axis='x', rotation=45)
        ax.grid(alpha=0.3, axis='y')

        # Activation sparsity (% of near-zero values)
        ax = axes[1, col]
        sparsity_data = []
        for cls_id in range(NUM_CLASSES):
            if cls_id in class_data and len(class_data[cls_id][key]) > 0:
                d = class_data[cls_id][key]
                sparsity = np.mean(np.abs(d) < 0.01) * 100  # % near-zero
                sparsity_data.append(sparsity)
            else:
                sparsity_data.append(0)

        bars = ax.bar(range(NUM_CLASSES), sparsity_data, color=CLASS_COLORS[:NUM_CLASSES],
                      edgecolor='none')
        ax.axvline(x=NUM_KNOWN - 0.5, color='red', linestyle='--', linewidth=1.5)
        ax.set_title(f'{name}\nSparsity (% |val|<0.01)', fontsize=10, fontweight='bold')
        ax.set_xticks(range(NUM_CLASSES))
        ax.set_xticklabels([LABEL_MAP[i][:6] for i in range(NUM_CLASSES)],
                          rotation=45, fontsize=8)
        ax.grid(alpha=0.3, axis='y')

        for bar, val in zip(bars, sparsity_data):
            if val > 0:
                ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.5,
                       f'{val:.1f}%', ha='center', va='bottom', fontsize=7)

    plt.suptitle('Feature Norm & Activation Sparsity per Class\n(Red dashed: Known/Unknown boundary)',
                 fontsize=14, fontweight='bold')
    plt.tight_layout()
    plt.savefig(f'{OUTPUT_DIR}/09_norms_and_sparsity.png', facecolor='white')
    plt.close()
    print(f"\n  [OK] Saved: {OUTPUT_DIR}/09_norms_and_sparsity.png")

    # Activation heatmap: per-class mean activation across final 32-d
    fig, ax = plt.subplots(figsize=(16, 6))
    mean_activations = []
    class_names_valid = []
    for cls_id in range(NUM_CLASSES):
        if cls_id in class_data and len(class_data[cls_id]['final_32']) > 0:
            mean_activations.append(class_data[cls_id]['final_32'].mean(axis=0))
            role = "K" if cls_id < NUM_KNOWN else "U"
            class_names_valid.append(f'{LABEL_MAP[cls_id]}({role})')
    mean_activations = np.array(mean_activations)

    im = ax.imshow(mean_activations, cmap='RdBu_r', aspect='auto',
                   vmin=-np.abs(mean_activations).max(), vmax=np.abs(mean_activations).max())
    ax.set_yticks(range(len(class_names_valid)))
    ax.set_yticklabels(class_names_valid, fontsize=9)
    ax.set_xlabel('Dimension')
    ax.set_title('Per-Class Mean Activation Heatmap (Final 32-d Feature)', fontsize=13, fontweight='bold')
    plt.colorbar(im, ax=ax, shrink=0.8, label='Mean activation')

    # Draw known/unknown boundary
    if len(class_names_valid) > NUM_KNOWN:
        ax.axhline(y=NUM_KNOWN - 0.5, color='red', linewidth=2)

    plt.tight_layout()
    plt.savefig(f'{OUTPUT_DIR}/09_activation_heatmap.png', facecolor='white')
    plt.close()
    print(f"  [OK] Saved: {OUTPUT_DIR}/09_activation_heatmap.png")


# ============================================================
# Analysis 10: Clustering-Oriented Feature Quality Assessment
# ============================================================
def analyze_clustering_quality(all_features, all_labels):
    """Evaluate feature quality for clustering tasks."""
    print("\n" + "=" * 70)
    print("Analysis 10: Clustering-Oriented Feature Quality Assessment")
    print("=" * 70)

    layers = [
        ('yamnet_128', 'yamnet 128-d'),
        ('fc1_128', 'FC1 128-d'),
        ('fc2_64', 'FC2 64-d'),
        ('final_32', 'Final 32-d')
    ]

    results = {}
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))

    metric_names = ['Silhouette (↑)', 'Davies-Bouldin (↓)']
    x_pos = np.arange(len(layers))
    bar_width = 0.2

    all_silhouette = []
    all_db = []

    for key, name in layers:
        data = all_features[key]

        # Full class clustering metrics
        sil = silhouette_score(data, all_labels, metric='euclidean', sample_size=min(5000, len(data)))
        db = davies_bouldin_score(data, all_labels)

        results[name] = {'silhouette': sil, 'davies_bouldin': db}

        print(f"\n  {name}:")
        print(f"    Silhouette Score:        {sil:.4f} (higher=better, range [-1, 1])")
        print(f"    Davies-Bouldin Index:    {db:.4f} (lower=better)")

        all_silhouette.append(sil)
        all_db.append(db)

        # Known-only vs Unknown-only
        known_mask = all_labels < NUM_KNOWN
        unknown_mask = all_labels >= NUM_KNOWN

        if known_mask.sum() > 100:
            sil_k = silhouette_score(data[known_mask], all_labels[known_mask],
                                     metric='euclidean', sample_size=min(3000, known_mask.sum()))
            db_k = davies_bouldin_score(data[known_mask], all_labels[known_mask])
            print(f"    Known classes only:      Sil={sil_k:.4f}, DB={db_k:.4f}")
        if unknown_mask.sum() > 100:
            sil_u = silhouette_score(data[unknown_mask], all_labels[unknown_mask],
                                     metric='euclidean', sample_size=min(3000, unknown_mask.sum()))
            db_u = davies_bouldin_score(data[unknown_mask], all_labels[unknown_mask])
            print(f"    Unknown classes only:    Sil={sil_u:.4f}, DB={db_u:.4f}")

    # Bar chart comparison
    axes[0].bar(x_pos, all_silhouette, color=['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728'],
                alpha=0.7, edgecolor='none')
    axes[0].set_xticks(x_pos)
    axes[0].set_xticklabels([n.split('(')[0].strip() for _, n in layers], rotation=30, fontsize=9)
    axes[0].set_ylabel('Silhouette Score (↑)')
    axes[0].set_title('Silhouette Score Comparison', fontsize=11, fontweight='bold')
    axes[0].grid(alpha=0.3, axis='y')
    for i, v in enumerate(all_silhouette):
        axes[0].text(i, v + 0.005, f'{v:.4f}', ha='center', fontsize=9)

    axes[1].bar(x_pos, all_db, color=['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728'],
                alpha=0.7, edgecolor='none')
    axes[1].set_xticks(x_pos)
    axes[1].set_xticklabels([n.split('(')[0].strip() for _, n in layers], rotation=30, fontsize=9)
    axes[1].set_ylabel('Davies-Bouldin Index (↓)')
    axes[1].set_title('Davies-Bouldin Index Comparison', fontsize=11, fontweight='bold')
    axes[1].grid(alpha=0.3, axis='y')
    for i, v in enumerate(all_db):
        axes[1].text(i, v + 0.01, f'{v:.4f}', ha='center', fontsize=9)

    plt.suptitle('Feature Clustering Quality Metrics', fontsize=14, fontweight='bold')
    plt.tight_layout()
    plt.savefig(f'{OUTPUT_DIR}/10_clustering_quality.png', facecolor='white')
    plt.close()
    print(f"\n  [OK] Saved: {OUTPUT_DIR}/10_clustering_quality.png")

    # Silhouette analysis per class for final 32-d
    data = all_features['final_32']
    from sklearn.metrics import silhouette_samples
    sample_sil = silhouette_samples(data, all_labels)

    fig, ax = plt.subplots(figsize=(14, 8))
    y_lower = 0
    for cls_id in range(NUM_CLASSES):
        mask = all_labels == cls_id
        cls_sil = sample_sil[mask]
        cls_sil.sort()
        cls_size = len(cls_sil)
        y_upper = y_lower + cls_size

        color = CLASS_COLORS[cls_id]
        ax.fill_betweenx(np.arange(y_lower, y_upper), 0, cls_sil,
                         facecolor=color, alpha=0.7, edgecolor=color, linewidth=0.5)
        role = "K" if cls_id < NUM_KNOWN else "U"
        ax.text(-0.05, (y_lower + y_upper) / 2, f'{LABEL_MAP[cls_id]}({role})',
                fontsize=8, verticalalignment='center')
        ax.text(sample_sil[mask].mean() + 0.02, (y_lower + y_upper) / 2,
                f'{sample_sil[mask].mean():.3f}', fontsize=7, verticalalignment='center')

        y_lower = y_upper + 5  # gap

    ax.axvline(x=sample_sil.mean(), color='red', linestyle='--',
               label=f'Mean: {sample_sil.mean():.3f}')
    ax.set_title('Silhouette Analysis per Class (Final 32-d Feature)', fontsize=13, fontweight='bold')
    ax.set_xlabel('Silhouette Coefficient')
    ax.set_ylabel('Samples (grouped by class)')
    ax.legend(fontsize=10)
    ax.set_yticks([])
    plt.tight_layout()
    plt.savefig(f'{OUTPUT_DIR}/10_silhouette_per_class.png', facecolor='white')
    plt.close()
    print(f"  [OK] Saved: {OUTPUT_DIR}/10_silhouette_per_class.png")

    return results


# ============================================================
# Bonus: Model Prediction Analysis
# ============================================================
def analyze_model_predictions(all_features, all_labels):
    """Analyze model prediction confidence and gating weights."""
    print("\n" + "=" * 70)
    print("Bonus: Model Prediction & Gating Weight Analysis")
    print("=" * 70)

    known_outputs = all_features['known_outputs']
    unknown_outputs = all_features['unknown_outputs']
    weights1 = all_features['weights1']
    weights2 = all_features['weights2']

    # Known classification confidence
    known_confidence = known_outputs.max(axis=1)
    known_pred = known_outputs.argmax(axis=1)

    fig, axes = plt.subplots(2, 3, figsize=(18, 10))

    # 1. Known prediction confidence distribution
    ax = axes[0, 0]
    known_mask = all_labels < NUM_KNOWN
    unknown_mask = all_labels >= NUM_KNOWN

    ax.hist(known_confidence[known_mask], bins=80, density=True, alpha=0.5,
            color='coral', label='True Known')
    ax.hist(known_confidence[unknown_mask], bins=80, density=True, alpha=0.5,
            color='steelblue', label='True Unknown')
    ax.set_title('Known Classifier Max Confidence', fontsize=10, fontweight='bold')
    ax.set_xlabel('Max Softmax Probability')
    ax.set_ylabel('Density')
    ax.legend(fontsize=8)
    ax.grid(alpha=0.3)

    # 2. "Unknown" class probability distribution
    ax = axes[0, 1]
    unknown_class_prob = known_outputs[:, -1]  # Last class = "unknown"
    ax.hist(unknown_class_prob[known_mask], bins=80, density=True, alpha=0.5,
            color='coral', label='True Known')
    ax.hist(unknown_class_prob[unknown_mask], bins=80, density=True, alpha=0.5,
            color='steelblue', label='True Unknown')
    ax.set_title('"Unknown" Class Probability', fontsize=10, fontweight='bold')
    ax.set_xlabel('P(unknown)')
    ax.set_ylabel('Density')
    ax.legend(fontsize=8)
    ax.grid(alpha=0.3)

    # 3. Classification accuracy per class
    ax = axes[0, 2]
    compressed_labels = np.where(all_labels < NUM_KNOWN, all_labels, NUM_KNOWN)
    acc_per_class = []
    for cls_id in range(NUM_CLASSES):
        mask = all_labels == cls_id
        if mask.sum() > 0:
            acc = np.mean(known_pred[mask] == compressed_labels[mask]) * 100
        else:
            acc = 0
        acc_per_class.append(acc)

    bars = ax.bar(range(NUM_CLASSES), acc_per_class, color=CLASS_COLORS[:NUM_CLASSES], edgecolor='none')
    ax.axvline(x=NUM_KNOWN - 0.5, color='red', linestyle='--', linewidth=1.5)
    ax.set_xticks(range(NUM_CLASSES))
    ax.set_xticklabels([LABEL_MAP[i][:6] for i in range(NUM_CLASSES)], rotation=45, fontsize=8)
    ax.set_ylabel('Accuracy (%)')
    ax.set_title('Classification Acc (compressed 7-class)', fontsize=10, fontweight='bold')
    ax.grid(alpha=0.3, axis='y')
    for bar, val in zip(bars, acc_per_class):
        if val > 0:
            ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 1,
                   f'{val:.1f}%', ha='center', fontsize=7)

    # 4. Expert gating weight distribution (weights1 - classifier)
    ax = axes[1, 0]
    expert_names = [f'Expert {i}' for i in range(weights1.shape[1])]
    for i in range(weights1.shape[1]):
        ax.hist(weights1[:, i], bins=50, density=True, alpha=0.5,
                label=expert_names[i])
    ax.set_title('Classifier Expert Gating Weights', fontsize=10, fontweight='bold')
    ax.set_xlabel('Weight')
    ax.set_ylabel('Density')
    ax.legend(fontsize=8)
    ax.grid(alpha=0.3)

    # 5. Expert gating weight distribution (weights2 - clusterer)
    ax = axes[1, 1]
    for i in range(weights2.shape[1]):
        ax.hist(weights2[:, i], bins=50, density=True, alpha=0.5,
                label=f'Expert {i}')
    ax.set_title('Clusterer Expert Gating Weights', fontsize=10, fontweight='bold')
    ax.set_xlabel('Weight')
    ax.set_ylabel('Density')
    ax.legend(fontsize=8)
    ax.grid(alpha=0.3)

    # 6. Unknown output entropy (clustering confidence)
    ax = axes[1, 2]
    eps = 1e-10
    unknown_entropy = -np.sum(unknown_outputs * np.log(unknown_outputs + eps), axis=1)
    max_entropy = np.log(unknown_outputs.shape[1])

    ax.hist(unknown_entropy[known_mask], bins=80, density=True, alpha=0.5,
            color='coral', label='True Known')
    ax.hist(unknown_entropy[unknown_mask], bins=80, density=True, alpha=0.5,
            color='steelblue', label='True Unknown')
    ax.axvline(x=max_entropy, color='green', linestyle='--', label=f'Max Entropy ({max_entropy:.2f})')
    ax.set_title('Clustering Output Entropy', fontsize=10, fontweight='bold')
    ax.set_xlabel('Entropy')
    ax.set_ylabel('Density')
    ax.legend(fontsize=8)
    ax.grid(alpha=0.3)

    plt.suptitle('Model Prediction & Gating Analysis', fontsize=14, fontweight='bold')
    plt.tight_layout()
    plt.savefig(f'{OUTPUT_DIR}/11_model_predictions.png', facecolor='white')
    plt.close()
    print(f"\n  [OK] Saved: {OUTPUT_DIR}/11_model_predictions.png")


# ============================================================
# Bonus: Layer Transition Analysis
# ============================================================
def analyze_layer_transitions(all_features, all_labels):
    """Analyze how features change through the FC projection layers."""
    print("\n" + "=" * 70)
    print("Bonus: Layer Transition Analysis")
    print("=" * 70)

    fig, axes = plt.subplots(1, 3, figsize=(18, 5))

    # Track class separation metric through layers
    layer_keys = ['yamnet_128', 'fc1_128', 'fc2_64', 'final_32']
    layer_names = ['yamnet', 'FC1', 'FC2', 'Final']

    # Compute silhouette score for each layer
    sil_scores = []
    for key in layer_keys:
        data = all_features[key]
        sil = silhouette_score(data, all_labels, metric='euclidean',
                              sample_size=min(3000, len(data)))
        sil_scores.append(sil)

    axes[0].plot(range(len(layer_names)), sil_scores, 'o-', color='steelblue',
                 linewidth=2, markersize=8)
    axes[0].set_xticks(range(len(layer_names)))
    axes[0].set_xticklabels(layer_names)
    axes[0].set_ylabel('Silhouette Score')
    axes[0].set_title('Class Separability through Layers', fontsize=11, fontweight='bold')
    axes[0].grid(alpha=0.3)
    for i, v in enumerate(sil_scores):
        axes[0].text(i, v + 0.003, f'{v:.4f}', ha='center', fontsize=9)

    # Average inter-class distance through layers
    avg_dists = []
    for key in layer_keys:
        data = all_features[key]
        centroids = []
        for cls_id in range(NUM_CLASSES):
            mask = all_labels == cls_id
            if mask.sum() > 0:
                centroids.append(data[mask].mean(axis=0))
        centroids = np.array(centroids)
        dists = pairwise_distances(centroids, metric='euclidean')
        # Average off-diagonal distance
        avg_dist = dists[np.triu_indices(len(centroids), k=1)].mean()
        avg_dists.append(avg_dist)

    axes[1].plot(range(len(layer_names)), avg_dists, 'o-', color='coral',
                 linewidth=2, markersize=8)
    axes[1].set_xticks(range(len(layer_names)))
    axes[1].set_xticklabels(layer_names)
    axes[1].set_ylabel('Avg Inter-Class Euclidean Distance')
    axes[1].set_title('Inter-Class Distance through Layers', fontsize=11, fontweight='bold')
    axes[1].grid(alpha=0.3)
    for i, v in enumerate(avg_dists):
        axes[1].text(i, v * 1.01, f'{v:.3f}', ha='center', fontsize=9)

    # Within-class variance through layers
    within_vars = []
    for key in layer_keys:
        data = all_features[key]
        total_var = 0
        for cls_id in range(NUM_CLASSES):
            mask = all_labels == cls_id
            if mask.sum() > 1:
                total_var += data[mask].var(axis=0).mean()
        within_vars.append(total_var / NUM_CLASSES)

    axes[2].plot(range(len(layer_names)), within_vars, 'o-', color='green',
                 linewidth=2, markersize=8)
    axes[2].set_xticks(range(len(layer_names)))
    axes[2].set_xticklabels(layer_names)
    axes[2].set_ylabel('Avg Within-Class Variance')
    axes[2].set_title('Within-Class Variance through Layers', fontsize=11, fontweight='bold')
    axes[2].grid(alpha=0.3)
    for i, v in enumerate(within_vars):
        axes[2].text(i, v * 1.01, f'{v:.4f}', ha='center', fontsize=9)

    plt.suptitle('Feature Transformation Analysis Across Layers', fontsize=14, fontweight='bold')
    plt.tight_layout()
    plt.savefig(f'{OUTPUT_DIR}/12_layer_transitions.png', facecolor='white')
    plt.close()
    print(f"\n  [OK] Saved: {OUTPUT_DIR}/12_layer_transitions.png")

    print("\n  Summary of layer transformations:")
    print(f"  {'Layer':12s} {'Silhouette':>12s} {'Inter-Dist':>12s} {'Intra-Var':>12s}")
    print("  " + "-" * 50)
    for i, name in enumerate(layer_names):
        print(f"  {name:12s} {sil_scores[i]:12.4f} {avg_dists[i]:12.4f} {within_vars[i]:12.4f}")


# ============================================================
# Main
# ============================================================
def main():
    print("=" * 70)
    print("yamnet + FC Projection Feature Space Analysis")
    print("=" * 70)
    print(f"Output directory: {OUTPUT_DIR}")
    print(f"Dataset: TAU-urban-acoustic-scenes-2022-mobile")
    print(f"  - Known classes (0-5): {', '.join(LABEL_MAP[i] for i in range(NUM_KNOWN))}")
    print(f"  - Unknown classes (6-9): {', '.join(LABEL_MAP[i] for i in range(NUM_KNOWN, NUM_CLASSES))}")

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    if torch.cuda.is_available():
        print(f"\nGPU: {torch.cuda.get_device_name(0)}")
        print(f"显存总量: {torch.cuda.get_device_properties(0).total_memory / 1024**3:.1f} GB")

    os.makedirs(OUTPUT_DIR, exist_ok=True)

    # ------------------------------------------------------------------
    # Load model
    # ------------------------------------------------------------------
    print("\n--- Loading Model ---")

    # Try loading a trained checkpoint; fall back to pretrained-yamnet + random FC
    checkpoint_path = 'experiment/yamnet_C2MoE_2stage/yamnet_C2MoE_2stage_trained_from0to120.pth'
    # checkpoint_path = None

    if checkpoint_path:
        print(f"  Loading trained checkpoint: {checkpoint_path}")
        checkpoint = torch.load(checkpoint_path, map_location=device)
        config = checkpoint.get('config', {})
        print(f"  Config: {config}")
        from training_model import FinalModel
        model = FinalModel.load(path = checkpoint_path)
        model = model.to(device)
        print(f"  Model loaded successfully from checkpoint.")
    else:
        print("  No trained checkpoint found. Loading pretrained yamnet with random FC layers.")
        from training_model import FinalModel
        model = FinalModel(
            num_unknown_classes=4,
            num_known_classes=6,
            reload_feature_model_pretrained=True
        ).to(device)
        print(f"  Model initialized (pretrained yamnet + random FC).")

    model.eval()
    print(f"  Total parameters: {sum(p.numel() for p in model.parameters()):,}")

    # ------------------------------------------------------------------
    # Load dataset
    # ------------------------------------------------------------------
    print("\n--- Loading Dataset ---")
    # train_dataset = TAUDataset(split='train')
    # calib_dataset = TAUDataset(split='calib', use_cache = True)
    test_dataset = TAUDataset(split='test', use_cache = True)
    print(f"  Dataset size: {len(test_dataset)}")

    # ------------------------------------------------------------------
    # Collect features
    # ------------------------------------------------------------------
    print("\n--- Collecting Features ---")
    class_data, all_features, all_labels = collect_features(
        model, test_dataset, device=device,
        max_samples_per_class=None,
        batch_size=512,
        split_name='calib'
    )

    # ------------------------------------------------------------------
    # Run all analyses
    # ------------------------------------------------------------------
    print("\n--- Running Analyses ---")

    analyze_overview(all_features, all_labels)

    analyze_per_class_stats(class_data)

    analyze_dimension_variance(all_features, all_labels)

    analyze_feature_distributions(class_data, n_dims_to_show=8)

    analyze_correlation(all_features, all_labels)

    analyze_feature_space_visualization(all_features, all_labels)

    analyze_inter_class_distance(class_data)

    analyze_known_vs_unknown(all_features, all_labels)

    analyze_feature_norms(class_data)

    cluster_results = analyze_clustering_quality(all_features, all_labels)

    analyze_model_predictions(all_features, all_labels)

    analyze_layer_transitions(all_features, all_labels)

    # ------------------------------------------------------------------
    # Summary
    # ------------------------------------------------------------------
    print("\n" + "=" * 70)
    print("Analysis Complete! Generated files:")
    print("=" * 70)

    output_files = sorted([f for f in os.listdir(OUTPUT_DIR) if f.endswith('.png')])
    for f in output_files:
        size = os.path.getsize(os.path.join(OUTPUT_DIR, f))
        print(f"  [chart] {f} ({size/1024:.1f} KB)")

    print(f"\nAll charts saved in: {OUTPUT_DIR}/")

    # Print feature quality summary
    print("\n" + "=" * 70)
    print("Feature Quality Summary:")
    print("=" * 70)
    for name, metrics in cluster_results.items():
        print(f"  {name}:")
        print(f"    Silhouette: {metrics['silhouette']:.4f}")
        print(f"    Davies-Bouldin: {metrics['davies_bouldin']:.4f}")

    print("=" * 70)


if __name__ == "__main__":
    main()